Add workshop content to docs site
particle-iot/docs pull request #948
Opened 2019-03-01 22:48 UTC by bsatrom

@interested1 and @rickkas7 this is a *draft* PR to add a Workshops section to the docs site. It's not done and needs the following before we can merge:

- [ ] Configure Left Nav for Workshops Section
- [ ] Move images into `assets` and update image links in content
- [ ] Configure header tables on section pages
- [ ] review and tweak main workshop landing page
- [ ] fix the keynote slide embeds

adding this now for our discussion and your review. Feel free to add any input here.

2019-03-07 15:27 UTC, bsatrom commented
Additional actions based on feedback from @interested1 

[ ] Add some text to each slide embed page so it doesn't look like an empty page
[ ] Make sure the step numbering is correct
[ ] Tweak the TOC with shorter names for the sidebar
[ ] Create a workshop landing page that links to other workshops

2019-03-20 18:44 UTC, bsatrom commented
@interested1 @rickkas7 marking this one as ready to review and potentially merge. LMK if you have any questions!

2019-03-21 18:33 UTC, rickkas7 approved these changes
Double check that one thing on metalsmith.js, otherwise looks good. I reviewed all of the technical changes and they look fine. I ran the modified version and the navigation looks good but I didn't look through all of the content.

2019-03-21 18:33 UTC, rickkas7 commented on scripts/metalsmith.js
> +      workshops: {
There are two workshops sections. One here and one on line 205. I don't think you want both.

2019-03-21 19:15 UTC, interested1 requested changes
OK, I believe I've pulled the most recent version and am on the correct branch. Here are a few things I found that need to be fixed before going live. 

- First off, the navigation looks great, Brandon. 

- Loading the slides still takes a bit of time — not sure if it's my internet connection or simply a slow load. http://localhost:8080/workshops/mesh-101-workshop/a-lap-around-particle/ was one of the slow loaders for me.

- Lack of step enumeration in the following sections: 
http://localhost:8080/workshops/photon-maker-kit-workshop/ch1/#mobile-app-instructions
AND http://localhost:8080/workshops/photon-maker-kit-workshop/ch2/
AND http://localhost:8080/workshops/photon-maker-kit-workshop/ch3/
AND http://localhost:8080/workshops/photon-maker-kit-workshop/ch4/
AND http://localhost:8080/workshops/photon-maker-kit-workshop/ch5/.

- Lack of step enumeration and code improperly formatted: http://localhost:8080/workshops/mesh-101-workshop/mesh-button-led/#remote-display

2019-03-21 21:17 UTC, bsatrom commented
@interested1 not really much I can do about the slow-loading slides. That's all on Apple...

I'll take a look at those other items now

2019-03-22 16:58 UTC, merged